### PR TITLE
Fix introduced dependency on anstream by auto-color

### PR DESCRIPTION
**Pull request by anacrolix**
Fixes https://github.com/rust-cli/env_logger/issues/337.

### CODE REVIEW

**Comment by epage** [comment]
I'm still not seeing what the problem is here.

**Comment by anacrolix** [comment]
@vantessel @sdroege might have some insight. 

Related:

https://github.com/rust-cli/env_logger/issues/312

https://github.com/rust-cli/env_logger/pull/304

**Comment by sdroege** [comment]
Yes, at this point this doesn't seem worth it anymore

**Comment by anacrolix** [comment]
auto-color creates a dependency on anstream when one should not exist. It confuses the tooling. I'm using nightly.

**Comment by epage** [comment]
What tooling does it confuse? Our CI passes and many other people use it.

**Comment by anacrolix** [comment]
https://github.com/rust-cli/env_logger/issues/337#issue-2574392620

**Comment by epage** [comment]
As its working everywhere else in Cargo, I'm assuming that is a bug in `cargo-udeps`.  As such, it should be addressed there.  Before opening an issue there, I would recommend making sure your install is up to date in case that is the issue.  They link against cargo and so if you are using a version with an old enough cargo, then yes it would be broken.

**Comment by bburdette** [comment]
Getting this message today, with cargo 1.77.1

**Pull request closed without merging**
